// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';


var Location = /* module */[];

var State = /* module */[];

var History = /* module */[
  /* Location */Location,
  /* State */State
];

exports.History = History;
/* No side effect */
