// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';

var Js_boolean        = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact       = require("reason-react/src/reasonReact.js");
var ReactRouterDom    = require("react-router-dom");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function optionToBool(optional) {
  if (optional) {
    return /* true */1;
  } else {
    return /* false */0;
  }
}

function make(exact, path, component, render, children) {
  return ReasonReact.wrapJsForReason(ReactRouterDom.Route, {
              exact: Js_boolean.to_js_boolean(optionToBool(exact)),
              path: Js_null_undefined.from_opt(path),
              component: Js_null_undefined.from_opt(component),
              render: Js_null_undefined.from_opt(render)
            }, children);
}

var Route = /* module */[/* make */make];

function make$1(_to, children) {
  return ReasonReact.wrapJsForReason(ReactRouterDom.NavLink, {
              to: _to
            }, children);
}

var NavLink = /* module */[/* make */make$1];

function make$2(children) {
  return ReasonReact.wrapJsForReason(ReactRouterDom.BrowserRouter, { }, children);
}

var BrowserRouter = /* module */[/* make */make$2];

exports.optionToBool  = optionToBool;
exports.Route         = Route;
exports.NavLink       = NavLink;
exports.BrowserRouter = BrowserRouter;
/* ReasonReact Not a pure module */
