// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';

var React                     = require("react");
var ReasonReact               = require("reason-react/src/reasonReact.js");
var ReactRouter$ReactTemplate = require("./bindings/reactRouter.bs.js");

var component = ReasonReact.statelessComponent("Header");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, "Hola soy el header");
    });
  return newrecord;
}

var Header = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("Movies");

function make$1() {
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, "Movies");
    });
  return newrecord;
}

var Movies = /* module */[
  /* component */component$1,
  /* make */make$1
];

function getMovies() {
  return ReasonReact.element(/* None */0, /* None */0, make$1(/* array */[]));
}

var component$2 = ReasonReact.statelessComponent("App");

function make$2() {
  var newrecord = component$2.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, ReactRouter$ReactTemplate.BrowserRouter[/* make */0](/* array */[React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, make(/* array */[])), React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, ReactRouter$ReactTemplate.Route[/* make */0](/* Some */[/* true */1], /* Some */["/"], /* Some */[getMovies], /* None */0, /* array */[]))))]));
    });
  return newrecord;
}

exports.Header    = Header;
exports.Movies    = Movies;
exports.getMovies = getMovies;
exports.component = component$2;
exports.make      = make$2;
/* component Not a pure module */
