// Generated by BUCKLESCRIPT VERSION 1.10.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe        = require("reason-react/src/reactDOMRe.js");
var ReasonReact       = require("reason-react/src/reasonReact.js");
var App$ReactTemplate = require("./app.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$ReactTemplate.make(/* array */[])), "index");

/*  Not a pure module */
